on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  sonarqube:
    name: Sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '14.17.4'
            cache: 'npm'
      - name: NPM Install
        run: npm install
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DO_REGISTRY_URL }}/thairod/thairod-nuxtjs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DO_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Build
        run: |
          docker build --pull -t ${{ env.IMAGE_NAME }}:$GITHUB_SHA .
          docker tag ${{ env.IMAGE_NAME }}:$GITHUB_SHA ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:$GITHUB_SHA
          docker push ${{ env.IMAGE_NAME }}:latest
          echo "Image ${{ env.IMAGE_NAME }}:$GITHUB_SHA pushed"
      - name: Docker Logout
        run: |
          docker logout "${{ secrets.DO_REGISTRY_URL }}"
